### ISSUE TITLE
Plot: Create sankey plot - ICTR

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltPlot#4]
The same as [issue](https://github.com/2DegreesInvesting/tiltPlot/issues/2) only for the ICTR

@lindadelacombaz once Plot: [Create sankey plot - PCTR #2](https://github.com/2DegreesInvesting/tiltPlot/issues/2) is done, please work on this one as well. 

BLOCKED until PCTR sankey plot is done.

**Comment by Tilmon** [comment]
@anne why does the title say "placeholder"? Is it because you first want to have the PCTR sankey plot done and then use the same approach for ICTR? If so, please move status to "BLOCKED", remove "placeholder" from title and explain in description why it's BLOCKED (i.e. because PCTR sankey plot to be finished first). 

Thank you!

**Comment by Tilmon** [comment]
Assigning this to @lindadelacombaz as she is leading the plot work now. 
cc' @AnneSchoenauer @maurolepore
