### ISSUE TITLE
Plot: Add options for the sankey plot function and modify the toy data set accordingly

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltPlot#5]
Dear Linda, 

You did great with the sankey plot. There is one enhancement that I would like to see in the sankey plot. You created the finance_weighing functions for this toy_data set [here ](https://docs.google.com/spreadsheets/d/1i4a_vGXTK2Zj_7MW528tEevUeQSPlqhJHl4xGg8MAMQ/edit#gid=0). Please note that I added bank_b, as this is more realistically for the loan data that I am using. Could you also add for the sankey plot those different possibilites of weighing the different loans?  

I know you find [this toy_data](https://docs.google.com/spreadsheets/d/1eN1J5Ew0WmLrnX7RIEt6VCz74qRdCeftPSVSpCc4jXA/edit#gid=1406180501) set to complicated for the sankey plots but it would mean that we have an additional column for best_case, worst_case and main_activity. 

The result would be that before running the sankey plot I am setting the option if I want to have equal_weight, best_case, worst_case or main_activity_weight. I think how the sankey plot runs right now it is on equal_weight assumption.  

Let me know if you have any questions. 
Thanks a lot. 
All the best
Anne

**Comment by Tilmon** [comment]
@AnneSchoenauer the title and task description is not entirely clear to me. Can you please update the description and specify the following? 
1. To which "plots" are you referring to specifically? All other plot-related tickets or specific ones? Probably best way is to link the related issues. 
2. What does placeholder mean? Do you mean it's a task that's still BLOCKED because plots first need to be finished? If so, please put Status on "BLOCKED" and make a note in the description why it's still blocked. 

This will help to tackle this task. Thank you!

**Comment by Tilmon** [comment]
@AnneSchoenauer the new task description is not entirely clear. Does the following fulfill your request? 

- for that, @lindadelacombaz needs to include the columns `equal_weight`, `best_case`, `worst_case `or `main_activity_weight` in her toy dataset and plot the sankey graph with those options? 
?

Question: How do you want this new weighting process to work? Please clarify.

**Comment by Tilmon** [comment]
@AnneSchoenauer I think it's best if @lindadelacombaz responses and rephrases the question :)
