### ISSUE TITLE
Clarify the input data for the plots with financial data

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltPlot#51]
> Clarify the input data for the plots, especially with regard to this issue [here](https://github.com/2DegreesInvesting/tiltIndicator/issues/474#event-9949409617).
-- @AnneSchoenauer 

See also #45 

Note for my future self:

I opened this issue on behalf of Anne, as I turned her roadmap from a list of TODOs in a google document into a collection of issues in the "[Insights](https://github.com/2DegreesInvesting/tiltPlot/milestone/1)" milestone.

**Comment by AnneSchoenauer** [comment]
So there are three kinds of plots. Please refer to the Google Document [here](https://docs.google.com/document/d/1YA9y9HdO864X91h-ferVZw660yvMdzKWBjq7UJwy0ro/edit#heading=h.4gyjt75gfscb) again. For each of the three kinds, we need a different dataset. 

_Please note that I only refer now to the product level as the input product level still needs some enhancement. So best to focus now only on the emission profile (former PCTR) and sector profile (former PSTR)._ 

**2. Financial insights**

This dataset is the dataset from step 1.2 in this issue here plus the financial data. To make the graphs that you can see in the tiltPlot package you would need to have at least: `bank_id/bank_group`, `credit_size/amount_total`, `amount_of_distinct_products`, `equal_weight_finance`, `worst_case_finance`, `best_case_finance`.  

You can find a toy dataset that Linda used for her plots [here](https://docs.google.com/spreadsheets/d/1i4a_vGXTK2Zj_7MW528tEevUeQSPlqhJHl4xGg8MAMQ/edit#gid=574477182)



Please note: While discussing this with you, I think we could for example also think about adding the `amount of distinct products` already in the datasets after pre-processing the data. Or the `best case` and `worst case` could also already be implemented in the tiltIndicatorAfter package. But for this, lets have new tickets and this also refers to the Bundesbank workflow with regard to where to put `*analysis_R` in the ecosystem. 

I hope this helps. Please let me know if you have any questions or you cannot find the real data for each of the steps. I think if we cannot find the real data that have such columns as described here, we would need to reach out to Kalash and Yana.

**Comment by maurolepore** [comment]
@AnneSchoenauer

I would consider this issue done and would close it. This indicates that you have provided the clarifications you think necessary to re-gain this context whenever we need this information to develop specific plots.

**Comment by AnneSchoenauer** [comment]
@maurolepore yes, I close it.
